version: '3.7'

services:
  mysql:
    image: mariadb:10.7.1
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root12344"
      MYSQL_DATABASE: "Pokemon"
      MYSQL_USER: "eich"
      MYSQL_PASSWORD: "eich12344"
    ports:
      - 3306:3306

volumes:
  mysql_data: