INSERT INTO Attacks VALUES ('Assurance', 'Dark', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Beat Up', 'Dark', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Bite', 'Dark', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Crunch', 'Dark', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Dark Pulse', 'Dark', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Dark Void', 'Dark', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Embargo', 'Dark', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Faint Attack', 'Dark', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Fake Tears', 'Dark', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Flatter', 'Dark', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Fling', 'Dark', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Knock Off', 'Dark', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Memento', 'Dark', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Nasty Plot', 'Dark', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Night Slash', 'Dark', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Payback', 'Dark', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Punishment', 'Dark', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Pursuit', 'Dark', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Snatch', 'Dark', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Sucker Punch', 'Dark', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Switcheroo', 'Dark', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Taunt', 'Dark', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Thief', 'Dark', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Torment', 'Dark', 1, 1, 1, 0);
