INSERT INTO Attacks VALUES ('Arm Thrust', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Aura Sphere', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Brick Break', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Bulk Up', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Close Combat', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Counter', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Cross Chop', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Detect', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Double Kick', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Drain Punch', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('DynamicPunch', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Focus Blast', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Focus Punch', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Force Palm', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Hammer Arm', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Hi Jump Kick', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Jump Kick', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Karate Chop', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Low Kick', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Mach Punch', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Revenge', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Reversal', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Rock Smash', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Rolling Kick', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Seismic Toss', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Sky Uppercut', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Submission', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Superpower', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Triple Kick', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Vacuum Wave', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Vital Throw', 'Fighting', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Wake-Up Slap', 'Fighting', 1, 1, 1, 0);
