INSERT INTO Attacks VALUES ('Blast Burn', 'Fire', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Blaze Kick', 'Fire', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Ember', 'Fire', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Eruption', 'Fire', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Fire Blast', 'Fire', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Fire Fang', 'Fire', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Fire Punch', 'Fire', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Fire Spin', 'Fire', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Flame Wheel', 'Fire', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Flamethrower', 'Fire', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Flare Blitz', 'Fire', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Heat Wave', 'Fire', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Lava Plume', 'Fire', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Magma Storm', 'Fire', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Overheat', 'Fire', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Sacred Fire', 'Fire', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Sunny Day', 'Fire', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Will-O-Wisp', 'Fire', 1, 1, 1, 0);
