INSERT INTO Attacks VALUES ('Aerial Ace', 'Flying', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Aeroblast', 'Flying', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Air Cutter', 'Flying', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Air Slash', 'Flying', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Bounce', 'Flying', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Brave Bird', 'Flying', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Chatter', 'Flying', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Defog', 'Flying', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Drill Peck', 'Flying', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('FeatherDance', 'Flying', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Fly', 'Flying', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Gust', 'Flying', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Mirror Move', 'Flying', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Peck', 'Flying', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Pluck', 'Flying', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Roost', 'Flying', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Sky Attack', 'Flying', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Tailwind', 'Flying', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Wing Attack', 'Flying', 1, 1, 1, 0);
