INSERT INTO Attacks VALUES ('Absorb', 'Grass', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Aromatherapy', 'Grass', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Bullet Seed', 'Grass', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Cotton Spore', 'Grass', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Energy Ball', 'Grass', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Frenzy Plant', 'Grass', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Giga Drain', 'Grass', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Grass Knot', 'Grass', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('GrassWhistle', 'Grass', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Ingrain', 'Grass', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Leaf Blade', 'Grass', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Leaf Storm', 'Grass', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Leech Seed', 'Grass', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Magical Leaf', 'Grass', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Mega Drain', 'Grass', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Needle Arm', 'Grass', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Petal Dance', 'Grass', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Power Whip', 'Grass', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Razor Leaf', 'Grass', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Seed Bomb', 'Grass', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Seed Flare', 'Grass', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Sleep Powder', 'Grass', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('SolarBeam', 'Grass', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Spore', 'Grass', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Stun Spore', 'Grass', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Synthesis', 'Grass', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Vine Whip', 'Grass', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Wood Hammer', 'Grass', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Worry Seed', 'Grass', 1, 1, 1, 0);
