INSERT INTO Attacks VALUES ('Bone Club', 'Ground', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Bone Rush', 'Ground', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Bonemerang', 'Ground', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Dig', 'Ground', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Earth Power', 'Ground', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Earthquake', 'Ground', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Fissure', 'Ground', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Magnitude', 'Ground', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Mud Bomb', 'Ground', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Mud Shot', 'Ground', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Mud Sport', 'Ground', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Mud-Slap', 'Ground', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Sand Tomb', 'Ground', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Sand-Attack', 'Ground', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Spikes', 'Ground', 1, 1, 1, 0);
