INSERT INTO Attacks VALUES ('Acupressure', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Assist', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Attract', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Barrage', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Baton Pass', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Belly Drum', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Bide', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Bind', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Block', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Body Slam', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Camouflage', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Captivate', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Charm', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Comet Punch', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Constrict', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Conversion', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Conversion 2', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Copycat', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Covet', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Crush Claw', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Crush Grip', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Cut', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Defense Curl', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Disable', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Dizzy Punch', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Double Hit', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Double Team', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Double-edge', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('DoubleSlap', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Egg Bomb', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Encore', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Endeavor', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Endure', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Explosion', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('ExtremeSpeed', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Facade', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Fake Out', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('False Swipe', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Feint', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Flail', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Flash', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Focus Energy', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Follow Me', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Foresight', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Frustration', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Fury Attack', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Fury Swipes', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Giga Impact', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Glare', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Growl', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Growth', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Guillotine', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Harden', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Headbutt', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Heal Bell', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Helping Hand', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Hidden Power', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Horn Attack', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Horn Drill', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Howl', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Hyper Beam', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Hyper Fang', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Hyper Voice', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Judgment', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Last Resort', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Leer', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Lock-On', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Lovely Kiss', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Lucky Chant', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Me First', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Mean Look', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Mega Kick', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Mega Punch', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Metronome', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Milk Drink', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Mimic', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Mind Reader', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Minimize', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Moonlight', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Morning Sun', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Natural Gift', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Nature Power', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Odor Sleuth', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Pain Split', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Pay Day', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Perish Song', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Pound', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Present', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Protect', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Psych Up', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Quick Attack', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Rage', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Rapid Spin', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Razor Wind', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Recover', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Recycle', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Refresh', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Return', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Roar', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Rock Climb', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Safeguard', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Scary Face', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Scratch', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Screech', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Secret Power', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Selfdestruct', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Sharpen', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Sing', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Sketch', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Skull Bash', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Slack Off', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Slam', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Slash', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Sleep Talk', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('SmellingSalt', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('SmokeScreen', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Snore', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Softboiled', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('SonicBoom', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Spike Cannon', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Spit Up', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Splash', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Stockpile', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Stomp', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Strength', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Struggle', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Substitute', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Super Fang', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Supersonic', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Swagger', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Swallow', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Sweet Kiss', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Sweet Scent', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Swift', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Swords Dance', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Tackle', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Tail Whip', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Take Down', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Teeter Dance', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Thrash', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Tickle', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Transform', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Tri Attack', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Trump Card', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Uproar', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Vicegrip', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Weather Ball', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Whirlwind', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Wish', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Wrap', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Wring Out', 'Normal', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Yawn', 'Normal', 1, 1, 1, 0);
