INSERT INTO Attacks VALUES ('Agility', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Amnesia', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Barrier', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Calm Mind', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Confusion', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Cosmic Power', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Dream Eater', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Extrasensory', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Future Sight', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Gravity', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Guard Swap', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Heal Block', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Healing Wish', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Heart Swap', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Hypnosis', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Imprison', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Kinesis', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Light Screen', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Lunar Dance', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Luster Purge', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Magic Coat', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Meditate', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Miracle Eye', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Mirror Coat', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Mist Ball', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Power Swap', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Power Trick', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Psybeam', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Psychic', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Psycho Boost', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Psycho Cut', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Psycho Shift', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Psywave', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Reflect', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Rest', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Role Play', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Skill Swap', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Teleport', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Trick', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Trick Room', 'Psychic', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Zen Headbutt', 'Psychic', 1, 1, 1, 0);
