INSERT INTO Attacks VALUES ('AncientPower', 'Rock', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Head Smash', 'Rock', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Power Gem', 'Rock', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Rock Blast', 'Rock', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Rock Polish', 'Rock', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Rock Slide', 'Rock', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Rock Throw', 'Rock', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Rock Tomb', 'Rock', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Rock Wrecker', 'Rock', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Rollout', 'Rock', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Sandstorm', 'Rock', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Stealth Rock', 'Rock', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Stone Edge', 'Rock', 1, 1, 1, 0);
