INSERT INTO Attacks VALUES ('Aqua Jet', 'Water', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Aqua Ring', 'Water', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Aqua Tail', 'Water', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Brine', 'Water', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Bubble', 'Water', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('BubbleBeam', 'Water', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Clamp', 'Water', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Crabhammer', 'Water', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Dive', 'Water', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Hydro Cannon', 'Water', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Hydro Pump', 'Water', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Muddy Water', 'Water', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Octazooka', 'Water', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Rain Dance', 'Water', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Surf', 'Water', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Water Gun', 'Water', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Water Pulse', 'Water', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Water Sport', 'Water', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Water Spout', 'Water', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Waterfall', 'Water', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Whirlpool', 'Water', 1, 1, 1, 0);
INSERT INTO Attacks VALUES ('Withdraw', 'Water', 1, 1, 1, 0);
